

<div class="footer-joinus">
  <p class="newsletter-text pc-only">ミレーの最新情報が届くニュースレターにご登録いただくと、<br>オンラインストアで使える<span>10％OFF</span>クーポンコードを差し上げます。</p>
  <p class="newsletter-text sp-only">ミレーの最新情報が届くニュースレターにご登録いただくと、オンラインストアで使える<span>10％OFF</span>クーポンコードを差し上げます。</p>
  <div class="newsletter_btn_wrap">
    <a class="newsletter_btn" href="https://www.millet.jp/p/newsletter/subscribe">ニュースレターに登録</a>
  </div>
  <!--
  <form name="header_join_as" method="post" action="" onsubmit="return false;" class="emailsignupheaderform" id="header_join_as">
    <input type="hidden" value="" name="transactionid">
    <input type="hidden" name="mode" value="">
    <div class="input-box">
      <input id="signupaddress" type="text" name="signupaddress" class="links_item_join-i" placeholder="Eメールアドレス" maxlength="512" autocapitalize="off" autocorrect="off" spellcheck="false" title="メールマガジンを購読" value="">
      <button id="join-pop-dyn" type="submit" title="送信" class="button move-button"><span><span>登録</span></span></button>
    </div>
  </form> -->
</div>






<footer>
  <div id="pageTop">▲</div>
  <div class="inner cf pc_parts footer-pc">
    <div class="f-link_box cf">
      <ul class="f-link_main">
        <li class="f_king_ttl">ミレーについて</li>
        <li><a href="https://www.millet.jp/company/">企業情報</a></li>
        <!--<li><a href="">採用情報</a></li>-->
        <li><a href="https://www.millet.jp/p/about/member-agreement/">ご利用規約</a></li>
        <li><a href="https://www.millet.jp/p/about/privacy-policy/">プライバシーポリシー</a></li>
        <li><a href="https://www.millet.jp/p/about/terms/">特商法取引法に基づく表記</a></li>
      </ul>
      <ul class="f-link_sub">
        <li class="f_king_ttl">カスタマーサポート</li>
        <li><a href="https://www.millet.jp/faq/">FAQ</a></li>
        <li><a href="https://www.millet.jp/faq/how_payment/">お支払方法について</a></li>
        <li><a href="https://www.millet.jp/faq/charge/">送料について</a></li>
        <li><a href="https://www.millet.jp/faq/warranty/">2年保証付き</a></li>
        <li><a href="https://www.millet.jp/contact/">お問い合わせ</a></li>
      </ul>
      <ul class="f-link_sub f-link_sub_v_spacebetween">
        <li>
          <ul>
            <li class="f_king_ttl">販売店</li>
            <li><a href="https://www.millet.jp/storelocator/">ショップリスト</a></li>
          </ul>
        </li>
        <li>
          <ul>
            <li class="f_king_ttl">FOLLOW US</li>
            <li><a href="https://www.millet.jp/blog/">ニュース</a></li>
            <li>
              <ul class="sns cf">
                <li><a href="https://twitter.com/millet_jp" target="_blank"><img src="https://milletonline.itembox.design/item/asset/img/icon_twitter.svg?t=20200306102807" alt="twitter" width="18px"></a></li>
                <li><a href="https://www.facebook.com/MILLET.jp/" target="_blank"><img src="https://milletonline.itembox.design/item/asset/img/icon_facebook.svg?t=20200306102807" alt="facebook" width="18px"></a></li>
                <li><a href="https://www.instagram.com/millet_jp/" target="_blank"><img src="https://milletonline.itembox.design/item/asset/img/icon_insta.svg?t=20200306102807" alt="instagram" width="18px"></a></li>
                <li><a href="https://line.me/R/ti/p/%40lfx0763c" target="_blank"><img src="https://milletonline.itembox.design/item/asset/img/icon_line.svg?t=20200306102807" alt="line" width="18px"></a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <div class="inner cf sp_parts footer-sp">
    <div class="f-sns">
      <h2 class="f-sns-title">FOLLOW US ON</h2>
      <ul class="f-sns-list">
        <li><a href="https://twitter.com/millet_jp" target="_blank"><img src="https://milletonline.itembox.design/item/asset/img/icon_twitter_sp.svg?t=20200306102807" alt="twitter" width="30px"></a></li>
        <li><a href="https://www.facebook.com/MILLET.jp/" target="_blank"><img src="https://milletonline.itembox.design/item/asset/img/icon_facebook_sp.svg?t=20200306102807" alt="facebook" width="30px"></a></li>
        <li><a href="https://www.instagram.com/millet_jp/" target="_blank"><img src="https://milletonline.itembox.design/item/asset/img/icon_insta_sp.svg?t=20200306102807" alt="instagram" width="30px"></a></li>
        <li><a href="https://line.me/R/ti/p/%40lfx0763c" target="_blank"><img src="https://milletonline.itembox.design/item/asset/img/icon_line_sp.svg?t=20200306102807" alt="line" width="30px"></a></li>
      </ul>
    </div>
    <ul class="f-main-menu">
      <li><a href="https://www.millet.jp/c/men/">﻿メンズ</a></li>
      <li><a href="https://www.millet.jp/c/women/">ウィメンズ</a></li>
      <li><a href="https://www.millet.jp/c/hardware/">バックパック（ハードウェア）</a></li>
      <li><a href="https://www.millet.jp/c/activities/">アクティビティ</a></li>
      <li><a href="https://www.millet.jp/c/outlet/">アウトレット</a></li>
      <li><a href="https://www.millet.jp/history/">ミレーの歴史</a></li>
      <li><a href="https://www.millet.jp/sustainability/">サスティナビリティ</a></li>
      <li><a href="https://www.millet.jp/blog/">ニュース</a></li>
      <li><a href="https://www.millet.jp/storelocator/">販売店</a></li>
    </ul>
    <ul class="f-sub-menu">
      <li><a href="https://www.millet.jp/p/login/">﻿ログイン</a></li>
      <li><a href="https://www.millet.jp/p/register/">新規会員登録</a></li>
      <li><a href="https://www.millet.jp/faq/">FAQ</a></li>
      <li><a href="https://www.millet.jp/contact/">お問い合わせ</a></li>
      <li><a href="https://www.millet.jp/company/">会社概要</a></li>
      <li><a href="https://www.millet.jp/p/about/member-agreement/">ご利用規約</a></li>
    </ul>
  </div>
  <div class="foot-logo-group">
    <div class="inner">
      <div class="bottom-logo-groupe">
        <div class="easycms-content easycms-layout-padding">
          <a title="CALIDA GROUP" href="http://www.calidagroup.com/" target="_blank"><img alt="CALIDA GROUP" src="https://milletonline.itembox.design/item/asset/img/logo-calidagroup.png?t=20200306102807"></a>
        </div>
        <ul>
          <li><a title="LAFUMA" href="http://www.lafuma.com/" target="_blank"><img alt="Lafuma" src="https://milletonline.itembox.design/item/asset/img/logo-lafuma.png?t=20200306102807"></a></li>
          <li><a title="LAFUMA MOBILIER" href="http://www.lafuma-mobilier.fr/" target="_blank"><img alt="Lafuma Mobilier" src="https://milletonline.itembox.design/item/asset/img/logo-lafuma-mobilier.png?t=20200306102807"></a></li>
          <li><img alt="Millet" src="https://milletonline.itembox.design/item/asset/img/logo-millet.png?t=20200306102807"></li>
          <li><a title="AUBADE" href="http://www.aubade.fr/" target="_blank"><img alt="Aubade" src="https://milletonline.itembox.design/item/asset/img/logo-aubade.png?t=20200306102807"></a></li>
          <li><a title="CALIDA" href="http://www.calida.com/fr-fr/" target="_blank"><img alt="CALIDA" src="https://milletonline.itembox.design/item/asset/img/logo-calida.png?t=20200306102807"></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-7679769-2"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'UA-7679769-2');
</script>
